# Orgs (spec 3.4): module.orgs is the whole org product, OIDC included. The
# OIDC client_id/client_secret it needs are minted here via the VCF
# Operations fleet-management IAM API (Mastercard/restapi provider), never
# carried by hand: vcfa_org_oidc's client_secret is not recoverable from
# VCFA once set, so hand-carrying it would mean it only ever lives in one
# person's clipboard.
#
# See README.md "State is credential-bearing" and "restapi provider
# limitations" sections before touching this file.

locals {
  oidc_orgs        = { for k, o in local.effective_orgs : k => o if o.oidc != null }
  local_admin_orgs = { for k, o in local.effective_orgs : k => o if o.local_admin != null }
}

# Recovery path for the failure mode the CLI state_import escape hatch can't
# reach: with an org's restapi_object.oauth_app instance missing from state,
# this file's other references to it (oauth_app_rotate_path's local below,
# module.orgs' client_id input) fail at eval time with "Invalid index" before
# a `terraform import` CLI call ever gets to commit anything. An import
# block doesn't have that problem because it's evaluated as part of the plan
# graph itself: a missing instance becomes a planned create/import for that
# resource, not a hard eval-time error on the cross-references elsewhere in
# this file. var.oauth_app_imports is empty by default, so this block is a
# no-op in normal operation. See README's escape-hatch section.
import {
  for_each = var.oauth_app_imports
  to       = restapi_object.oauth_app[each.key]
  id       = each.value
}

# Creates one OAuth App per org under the Ops SSO realm. The create response
# (clientId, clientSecret, issuerUrl) is captured via write_returns_object /
# create_returns_object on the provider (see provider.tf).
#
# redirectUrls/logoutUrls are derived from var.vcfa_url and the org name via
# var.oauth_app_url_pattern rather than hard-coded per org (see README's
# "OAuth app redirect/logout URLs" section for what's confirmed vs guessed).
# The true OIDC redirect URI is only known once module.orgs computes it
# (oidc_redirect_uri output, generated by VCFA itself after federation is
# created), which happens strictly after this resource on first apply -- so
# this value is a best-effort registration, not a verified one.
resource "restapi_object" "oauth_app" {
  for_each = local.oidc_orgs

  path          = "/suite-api/api/fleet-management/iam/ssorealms/${var.sso_realm_id}/oauth-apps"
  create_method = "POST"
  # oauth-apps objects carry two distinct identifiers: `id` (what every API
  # path parameter, including rotate, actually wants) and `clientId` (the
  # OAuth client id used in the OIDC handshake). id_attribute must be "id"
  # so .id resolves to the value the API's paths expect. Confirmed live:
  # GET/rotate by clientId 404s ("No such id"), GET/rotate by id works.
  id_attribute = "id"

  data = jsonencode({
    clientName   = "VCFA - ${each.value.name}"
    description  = "OIDC client for VCFA org ${each.value.name}, managed by provider-private-cloud."
    redirectUrls = [format(var.oauth_app_redirect_url_pattern, var.vcfa_url, each.value.name)]
    logoutUrls   = [format(var.oauth_app_logout_url_pattern, var.vcfa_url, each.value.name)]
  })

  # The Ops IAM oauth-apps API has no update operation: create (POST), read
  # (single/list GET), and rotate (POST) only, confirmed against the live
  # API on 2026-08-03 (a PUT here returns 500 "Internal Server error, cause
  # unknown" for every field, not a validation error on any one of them).
  # ignore_changes on data stops Terraform from ever attempting that PUT
  # because of drift between imported state and this resource's config
  # (clientName, redirectUrls, logoutUrls). A real payload change still
  # needs to reach the server: do that with a targeted replace instead of
  # editing data in place, e.g.
  #   terraform apply -replace='restapi_object.oauth_app["<key>"]'
  # This recreates the OAuth app and cascades a new clientId/clientSecret
  # into the org's OIDC config (oidc_client_secret, below): that cascade is
  # intentional given how the secret is wired downstream, not a bug to work
  # around.
  #
  # create_method, id_attribute, ignore_all_server_changes, and debug are
  # provider-local attributes: the restapi provider tracks them in state to
  # remember how it should manage the object, but none of them describe
  # anything the API server holds, and none of them affect anything
  # observable outside this provider's own bookkeeping. An import (see the
  # state_import escape hatch above) leaves them unset in the imported
  # state, which then shows up as a plan diff against this config on the
  # next run even though nothing about the object changed. This resource
  # has no working PUT (see above): resourceRestAPIUpdate in the v2.0.1
  # source calls updateObject() unconditionally whenever ANY tracked
  # attribute has a diff, not only when data changes, so leaving any one of
  # these four unignored produces the same broken-PUT 500 as a real data
  # change would. ignore_changes on all four, same as on data, keeps config
  # authoritative for new creates while leaving already-imported state
  # alone. Confirmed against run 30840012739's residual diff: create_method,
  # id_attribute, and ignore_all_server_changes appearing as "+ create" and
  # debug as "-> null" were the only remaining changes once data was
  # already ignored, and after this change none of the four show up on a
  # plan against that same state.
  #
  # debug's credential-logging risk was raised in review and considered
  # explicitly, not overlooked: setting debug = false in config so it stays
  # authoritative (rather than ignoring it) was tried and rejected, because
  # that reintroduces exactly the failure this resource's other three
  # ignore_changes entries exist to avoid (config-vs-state diff -> PUT ->
  # 500), and a targeted replace to clear a stale imported true mints a new
  # clientId and cascades churn through the org's live OIDC config, which
  # is worse than the risk it would fix. The risk itself doesn't apply
  # here: the restapi provider's debug output goes through Go's
  # log.Printf, which Terraform only surfaces as provider logs when TF_LOG
  # is set on the run; this pipeline never sets TF_LOG, so nothing is
  # printed regardless of what value debug holds in state, imported or
  # otherwise. ignore_changes on debug is therefore safe: the flag's value
  # has no observable effect in this environment either way.
  lifecycle {
    ignore_changes = [data, create_method, id_attribute, ignore_all_server_changes, debug]
  }
}

locals {
  # Full path to each org's rotate action. Computed as a local (not inline
  # in the resource below) because a resource block cannot reference its
  # own other arguments, and this same path is used for both the create
  # and update method overrides.
  #
  # .id below is the object id now that id_attribute above is "id"; this
  # reference didn't need to change, only what it resolves to did.
  oauth_app_rotate_path = {
    for k, o in local.oidc_orgs :
    k => "/suite-api/api/fleet-management/iam/ssorealms/${var.sso_realm_id}/oauth-apps/${restapi_object.oauth_app[k].id}/rotate"
  }

  # The oauth_app_rotate resource below has no real GET-able counterpart
  # (the rotate path is a bare POST action), so it needs an explicit
  # read_path override pointing back at the underlying OAuth app object
  # instead. See the long comment on oauth_app_rotate for why this is
  # required on Mastercard/restapi v2.0.1, not optional polish.
  oauth_app_read_path = {
    for k, o in local.oidc_orgs :
    k => "/suite-api/api/fleet-management/iam/ssorealms/${var.sso_realm_id}/oauth-apps/${restapi_object.oauth_app[k].id}"
  }
}

# Rotation is on-demand, never on every apply (ruling 4). This resource
# does not model a real CRUD object: POST .../rotate is a bare imperative
# action, not something with GET/PUT/DELETE semantics, and the restapi
# provider has no first-class "fire once when a trigger changes, otherwise
# zero-diff" primitive for that shape. The closest honest fit:
#
#   - `data` holds only `rotation_id`. As long as var.orgs[*].oidc.rotation_id
#     is unchanged, `data` doesn't change, so Terraform issues no API call
#     and the plan is clean and empty for this resource.
#   - A `rotation_id` change forces a full replace (destroy the terraform
#     object, then re-create it), never an in-place update. See the
#     replace_triggered_by comment below for why this changed from the
#     original update-in-place shape.
#
# On first apply (object doesn't exist yet), Terraform calls CREATE, which
# also targets the rotate path (create_method/path below): the org's OAuth
# app is rotated immediately after being minted. This is deliberate, not
# an oversight -- it makes the rotate resource's response the single
# source of truth for "the org's current client secret" in every case,
# including the very first apply, rather than needing to special-case
# "first secret came from create, every secret after came from rotate."
#
# read_path / destroy_path / force-replace (all v2.0.1-specific, confirmed
# against Mastercard/terraform-provider-restapi v2.0.1 source --
# restapi/resource_api_object.go and restapi/api_object.go): unlike the
# plugin-framework v3 line, this SDKv2-based generation always calls the
# resource's Read on every `terraform plan`/`apply` refresh, regardless of
# ignore_all_server_changes (that flag only suppresses drift-correction on
# `data`, not the GET call itself). Two consequences follow from there
# being no real GET-able endpoint for a bare POST action, and both needed
# a fix, not just a comment:
#
#   1. Left at its default read_path (path/{id}, i.e. the rotate path with
#      this resource's synthetic object_id appended), that GET 404s every
#      time. A 404 makes the provider clear the object's id, and Terraform
#      then treats the resource as deleted, forcing a recreate (and
#      therefore a real rotate call) on every single apply -- exactly the
#      "never on every apply" behavior this resource exists to prevent.
#      Fixed by pointing read_path at the underlying OAuth app's real
#      object endpoint instead (confirmed GET-able, same id used by
#      oauth_app's own read_path default): that keeps the id valid across
#      refreshes, and is harmless since ignore_all_server_changes still
#      prevents that read from ever rewriting `data`.
#   2. That same fix has a side effect: because the read now genuinely
#      hits the OAuth app object, not the rotate action, its response does
#      not contain clientSecret. api_object.go's readObject() overwrites
#      api_response on every call regardless of what it read, so relying
#      on api_response for the secret (the original design) means the
#      very next plan-only refresh after any rotation clobbers it, and
#      module.orgs' jsondecode(...)["clientSecret"] reference below would
#      then fail on a missing key. create_response doesn't have this
#      problem: confirmed in resource_api_object.go, it's set exactly once
#      per CREATE call and is never touched by Read or Update. So
#      oidc_client_secret (module.orgs, below) reads create_response, not
#      api_response, and this resource is forced to go through CREATE on
#      every rotation (never UPDATE) via the replace_triggered_by lifecycle
#      block, so create_response is always the latest rotation's response.
#
# destroy_method/destroy_path are overridden to a harmless GET against the
# same real, known-working OAuth app endpoint read_path already uses,
# instead of the SDK's default DELETE to a garbage path (path/{id}, same
# broken shape read_path had). There is still no server-side DELETE for a
# rotation action -- that hasn't changed, and removing this resource from
# config (or an org's oidc block) is still unsupported, see below -- but
# the replace_triggered_by lifecycle now makes an internal destroy-then-
# create cycle a normal, routine part of every deliberate rotation, not
# just a hypothetical from removing config. Leaving the default DELETE in
# place for that routine cycle would depend on an untested assumption
# (that an unverified path 404s cleanly rather than 405s or worse) on
# every single rotation; a GET against a URL already confirmed to succeed
# removes that risk entirely, since it can't fail or delete anything.
resource "restapi_object" "oauth_app_rotate" {
  for_each = local.oauth_app_rotate_path

  path           = each.value
  object_id      = "${each.key}-rotation"
  create_method  = "POST"
  update_method  = "POST"
  update_path    = each.value
  read_path      = local.oauth_app_read_path[each.key]
  destroy_method = "GET"
  destroy_path   = local.oauth_app_read_path[each.key]

  ignore_all_server_changes = true

  data = jsonencode({
    rotation_id = local.oidc_orgs[each.key].oidc.rotation_id
  })

  # Forces a destroy+create replace whenever rotation_id changes, instead
  # of the SDK's default in-place update. terraform_data is Terraform's own
  # built-in no-op resource (Terraform >= 1.4, no provider declaration
  # needed): its `input` mirrors rotation_id, so it only shows a diff when
  # rotation_id actually changes, and replace_triggered_by only fires a
  # replace when its referenced resource shows a diff. See the long
  # comment above the resource for why UPDATE (in-place) was the wrong
  # shape once create_response became the secret's source of truth.
  lifecycle {
    replace_triggered_by = [terraform_data.oauth_app_rotation_trigger[each.key]]
  }
}

resource "terraform_data" "oauth_app_rotation_trigger" {
  for_each = local.oidc_orgs

  input = each.value.oidc.rotation_id
}

module "orgs" {
  source   = "sentania-labs/org/vcfa"
  version  = "~> 0.1.0"
  for_each = local.effective_orgs

  name         = each.value.name
  display_name = each.value.display_name
  description  = each.value.description
  is_enabled   = each.value.is_enabled

  # local_admin is deliberately not passed through to the module: the
  # module's local_admin.role_ids wants raw role reference ids, which only
  # exist once the org itself exists (see the root-level data.vcfa_role +
  # vcfa_org_local_user below this module block). Feeding this module call
  # a role id resolved from its own output would be a circular dependency.
  local_admin          = null
  local_admin_password = null

  oidc = each.value.oidc == null ? null : {
    # .id is the object id (see id_attribute above); the OIDC handshake
    # needs clientId instead, read from api_data (populated from the
    # create/read response via write_returns_object/create_returns_object
    # in provider.tf). clientId is a plain string field, so api_data's
    # fmt-formatted map entry for it is the value as-is.
    client_id              = restapi_object.oauth_app[each.key].api_data["clientId"]
    wellknown_endpoint     = var.oidc_wellknown_endpoint
    scopes                 = each.value.oidc.scopes
    ui_button_label        = each.value.oidc.ui_button_label
    max_clock_skew_seconds = each.value.oidc.max_clock_skew_seconds
    prefer_id_token        = each.value.oidc.prefer_id_token
    groups                 = each.value.oidc.groups
  }
  # create_response, not api_response: see the long comment on
  # oauth_app_rotate above. create_response is documented (Mastercard/
  # restapi v2.0.1 docs) as "the raw body of the HTTP response returned
  # when creating the object," and confirmed in v2.0.1 source
  # (resource_api_object.go's resourceRestAPICreate) to be set exactly
  # once per CREATE call and never touched by a subsequent Read or Update.
  # api_response, by contrast, gets overwritten by every refresh-triggered
  # Read -- including reads against read_path, which points at the
  # underlying OAuth app object and never returns clientSecret -- so it
  # would go stale (and crash this jsondecode on the missing key) the
  # first time `terraform plan` runs after any apply that touched this
  # resource. create_response doesn't have that problem, and stays correct
  # because oauth_app_rotate's replace_triggered_by lifecycle block forces
  # every rotation through CREATE, never UPDATE.
  oidc_client_secret = each.value.oidc == null ? null : jsondecode(restapi_object.oauth_app_rotate[each.key].create_response)["clientSecret"]
}

# Break-glass local admin user, created at root rather than inside
# module.orgs (see the local_admin=null comment on the module call above).
# data.vcfa_role resolves the configured role NAME to the raw role id VCFA
# actually wants, scoped to the org that now exists via module.orgs[key].id.
# No cycle: module.orgs[key] is already fully specified by the time this
# data source reads it, it doesn't depend on this lookup's result.
data "vcfa_role" "local_admin" {
  for_each = local.local_admin_orgs

  name   = each.value.local_admin.role_name
  org_id = module.orgs[each.key].id
}

resource "vcfa_org_local_user" "local_admin" {
  for_each = local.local_admin_orgs

  org_id   = module.orgs[each.key].id
  username = each.value.local_admin.username
  password = var.local_admin_passwords[each.key]
  role_ids = [data.vcfa_role.local_admin[each.key].id]
}
